repos:
    - repo: local
      hooks:
          - id: keybind
            name: keybind
            entry: npm run keybind
            language: system
            pass_filenames: false
    - repo: https://github.com/pre-commit/mirrors-eslint
      rev: v8.56.0
      hooks:
          - id: eslint
            additional_dependencies:
                - "@typescript-eslint/eslint-plugin@7.3.1"
                - "@typescript-eslint/parser@7.3.1"
                - "eslint-config-prettier@9.1.0"
                - "eslint-plugin-import@2.29.1"
                - "eslint-plugin-prettier@5.1.3"
                - "eslint@8.56.0"
                - "prettier@3.1.0"
                - "typescript-eslint@7.3.1"
                - "typescript@5.4.2"
            files: \.(js|ts|cjs)$
            types: [file]
            args: ["--fix"]
    - repo: https://github.com/pre-commit/mirrors-prettier
      rev: v3.1.0
      hooks:
          - id: prettier
            args: ["--ignore-path", ".gitignore", "--ignore-path", ".prettierignore", "--write"]
    - repo: https://github.com/JohnnyMorganz/StyLua
      rev: v0.20.0
      hooks:
          - id: stylua-github
    - repo: local
      hooks:
          - id: test-compile
            name: test compile
            entry: npm run test-compile
            files: \.ts$
            language: system
            pass_filenames: false
