name: Check Style and Quality

on: [pull_request, push]

jobs:
    lint:
        name: Lint
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            # python is required for the "pre-commit" action.
            - uses: actions/setup-python@v3
            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: "18"
                  cache: "npm"
            - name: npm install
              run: npm ci --silent
            - uses: pre-commit/action@v3.0.1
